@extends('layouts.moderator-panel')
@section('title', $pageTitle.' · Moderación NexoEco')
@section('moderator-content')
<div class="mod-section-heading"><div><h2>Publicaciones</h2><p>Busca productos, consulta sus detalles y elimina contenido inapropiado. La publicación es directa.</p></div><span class="mod-count">{{ $counts['publicaciones'] }} productos publicados</span></div>
<div class="mod-review-layout"><section class="mod-card mod-publications"><div class="mod-list-toolbar"><nav class="mod-tabs" aria-label="Filtrar publicaciones">@foreach(['' => 'Publicadas', 'reportada' => 'Reportadas', 'eliminada' => 'Eliminadas'] as $state => $label)<a class="{{ (request('estado') ?? '') === $state ? 'active' : '' }}" href="{{ route(request()->route()->getName(), array_filter(['estado' => $state, 'q' => request('q')])) }}">{{ $label }}</a>@endforeach</nav></div>
<div class="mod-table-wrap"><table class="mod-table"><thead><tr><th>Publicación</th><th>Vendedor</th><th>Estado</th><th>Fecha</th><th><span class="sr-only">Revisar</span></th></tr></thead><tbody>@forelse($productos as $producto)
@php($image = \App\Support\MarketplaceImage::url($producto->imagenPrincipal?->imagen_url ?: $producto->imagen_url))
<tr class="{{ $seleccionado?->getKey() === $producto->getKey() ? 'selected' : '' }}"><td><a class="mod-product-cell" href="{{ route(request()->route()->getName(), array_merge(request()->only('q','estado','page'), ['seleccion' => $producto->getKey()])) }}">@if($image)<img src="{{ $image }}" alt="" loading="lazy">@else<span class="mod-thumbnail-empty"><x-mod-icon name="file"/></span>@endif<div><strong>{{ $producto->nombre_producto }}</strong><small>{{ $producto->categoria?->nombre_categoria ?? 'Sin categoría' }} · ${{ number_format($producto->precio, 2) }}</small></div></a></td><td><span class="mod-store-name">{{ $producto->tienda?->nombre_tienda ?? 'Tienda eliminada' }}</span></td><td>@include('moderador.partials.status', ['state' => $producto->trashed() ? 'eliminada' : 'publicada'])</td><td class="mod-date">{{ $producto->fecha_publicacion?->format('d/m/Y H:i') ?? 'Sin fecha' }}</td><td><a class="mod-row-arrow" href="{{ route(request()->route()->getName(), array_merge(request()->only('q','estado','page'), ['seleccion' => $producto->getKey()])) }}" aria-label="Revisar {{ $producto->nombre_producto }}"><x-mod-icon name="arrow"/></a></td></tr>
@empty<tr><td colspan="5"><div class="mod-empty"><x-mod-icon name="file"/><h3>No hay publicaciones{{ request('estado') ? ' en este estado' : '' }}</h3><p>Los productos se publican directamente y pueden consultarse aquí.</p></div></td></tr>@endforelse</tbody></table></div><div class="mod-pagination">{{ $productos->links() }}</div></section>
<aside class="mod-card mod-preview" aria-label="Vista previa de la publicación">@if($seleccionado)<div class="mod-preview-heading"><div><small>Vista previa</small><strong>PUB-{{ $seleccionado->getKey() }}</strong></div>@include('moderador.partials.status', ['state' => $seleccionado->trashed() ? 'eliminada' : 'publicada'])</div><div class="mod-preview-body">@php($previewImage = \App\Support\MarketplaceImage::url($seleccionado->imagenPrincipal?->imagen_url ?: $seleccionado->imagen_url))<div class="mod-preview-image">@if($previewImage)<a href="{{ $previewImage }}" target="_blank" rel="noopener" aria-label="Ampliar imagen del producto"><img src="{{ $previewImage }}" alt="{{ $seleccionado->nombre_producto }}"><span><x-mod-icon name="eye"/></span></a>@else<x-mod-icon name="file"/>@endif</div><h2>{{ $seleccionado->nombre_producto }}</h2><p class="mod-preview-price">${{ number_format($seleccionado->precio, 2) }} <small>MXN</small></p><p class="mod-content-text">{{ $seleccionado->descripcion ?: 'Sin descripción' }}</p><dl class="mod-data"><dt>Tienda</dt><dd>{{ $seleccionado->tienda?->nombre_tienda }}</dd><dt>Vendedor</dt><dd>{{ $seleccionado->tienda?->user?->name }}</dd><dt>Categoría</dt><dd>{{ $seleccionado->categoria?->nombre_categoria }}</dd></dl>@if($seleccionado->trashed() && $seleccionado->motivo_moderacion)<div class="mod-notice">{{ $seleccionado->motivo_moderacion }}</div>@endif @include('moderador.partials.delete-form', ['tipo' => 'productos', 'content' => $seleccionado])</div>@else<div class="mod-empty"><x-mod-icon name="eye"/><p>Selecciona una publicación para consultar sus datos.</p></div>@endif</aside></div>
@endsection
