<div class="admin-heading"><span class="buyer-eyebrow">Revisión · Vendedores</span><h1>Solicitud #{{ $solicitud->id_solicitud }}</h1><p class="buyer-description">{{ $solicitud->usuario->nombre_completo ?: $solicitud->usuario->name }} · {{ str_replace('_', ' ', $solicitud->estado) }}</p></div>
<div class="admin-columns"><section class="buyer-panel"><h2>Datos y documentos</h2><dl class="admin-data"><dt>Correo</dt><dd>{{ $solicitud->usuario->email }}</dd><dt>Verificación</dt><dd>{{ $solicitud->usuario->hasVerifiedEmail() ? 'Correo verificado' : 'Pendiente de verificar' }}</dd><dt>RFC</dt><dd>{{ $solicitud->rfc ?: 'Sin registrar' }}</dd><dt>CURP</dt><dd>{{ $solicitud->curp ?: 'Sin registrar' }}</dd><dt>Teléfono</dt><dd>{{ $solicitud->telefono ?: 'Sin registrar' }}</dd><dt>Domicilio fiscal</dt><dd>{{ $solicitud->domicilio_fiscal ?: 'Sin registrar' }}</dd></dl><div class="admin-document-list">
@forelse($solicitud->documentos as $document)
    @php($documentLabel = ['identificacion_frente' => 'Identificación · frente', 'identificacion_reverso' => 'Identificación · reverso', 'constancia_fiscal' => 'Constancia fiscal', 'comprobante_domicilio' => 'Comprobante de domicilio'][$document->tipo_documento] ?? $document->tipo_documento)
    <details class="admin-document" data-document-preview>
        <summary><div><strong>{{ $documentLabel }}</strong><span>{{ $document->nombre_original }} · Mostrar vista previa</span></div><svg class="admin-document-chevron" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" aria-hidden="true"><path d="m6 9 6 6 6-6" stroke-linecap="round" stroke-linejoin="round"/></svg></summary>
        <div class="admin-document-preview">
            @if(in_array($document->mime_type, ['image/jpeg', 'image/png', 'image/webp']))
                <img data-preview-src="{{ route($routePrefix.'.solicitudes.preview', [$solicitud, $document]) }}" alt="Vista previa de {{ $documentLabel }}" loading="lazy">
            @elseif($document->mime_type === 'application/pdf')
                <iframe data-preview-src="{{ route($routePrefix.'.solicitudes.preview', [$solicitud, $document]) }}" title="Vista previa de {{ $documentLabel }}" loading="lazy" referrerpolicy="same-origin"></iframe>
                <p class="buyer-muted">Si tu navegador no muestra el PDF, puedes abrirlo en otra pestaña.</p>
            @else
                <p class="buyer-muted">Este formato no admite vista previa.</p>
            @endif
            <div class="admin-document-actions"><a class="admin-action-button" href="{{ route($routePrefix.'.solicitudes.preview', [$solicitud, $document]) }}" target="_blank" rel="noopener">Abrir en otra pestaña</a><a class="admin-action-button" href="{{ route($routePrefix.'.solicitudes.document', [$solicitud, $document]) }}">Descargar archivo</a></div>
        </div>
    </details>
@empty<p>No hay documentos enviados.</p>@endforelse</div></section>
<section class="buyer-panel"><h2>Resultado de la revisión</h2>@if($solicitud->estaEnRevision())<p>Solo aprueba solicitudes con todos los documentos revisados y el correo verificado.</p><form class="buyer-form" method="POST" action="{{ route($routePrefix.'.solicitudes.review', $solicitud) }}" style="margin-top:24px;">@csrf<div class="buyer-field"><label for="estado">Decisión</label><select id="estado" name="estado" required><option value="">Selecciona una decisión</option><option value="aprobada" @selected(old('estado') === 'aprobada')>Aprobar vendedor</option><option value="requiere_correccion" @selected(old('estado') === 'requiere_correccion')>Solicitar correcciones</option><option value="rechazada" @selected(old('estado') === 'rechazada')>Rechazar solicitud</option></select></div><div class="buyer-field"><label for="motivo_revision">Mensaje para el usuario</label><textarea id="motivo_revision" name="motivo_revision" minlength="10" maxlength="2000">{{ old('motivo_revision') }}</textarea><p class="buyer-muted">Obligatorio al solicitar correcciones o rechazar.</p></div><button class="buyer-button" type="submit">Guardar revisión</button></form>@else<p>Esta solicitud no está pendiente de revisión.</p>@if($solicitud->motivo_revision)<div class="buyer-notice buyer-review-text">{{ $solicitud->motivo_revision }}</div>@endif<p class="buyer-muted">{{ $solicitud->fecha_revision?->format('d/m/Y H:i') }} @if($solicitud->moderador)· Revisada por {{ $solicitud->moderador->name }}@endif</p>@endif</section></div>
<a class="buyer-text-link" href="{{ route($returnRoute) }}">Volver a solicitudes</a>
