@extends('layouts.seller-panel')
@section('title', 'Mi tienda | NexoEco')
@section('seller-content')
@php
    $logo = \App\Support\MarketplaceImage::url($tienda->logo_tienda);
    $cover = \App\Support\MarketplaceImage::url($tienda->portada_tienda);
    $approved = $solicitud?->estaAprobada();
    $rating = $tienda->opiniones_avg_calificacion;
@endphp
<section class="seller-store-hero">
    <div class="seller-cover">@if($cover)<img src="{{ $cover }}" alt="Portada de {{ $tienda->nombre_tienda }}">@else<div class="seller-cover-empty"><x-seller-icon/><span>El espacio de tu negocio</span></div>@endif<a class="seller-cover-edit" href="{{ route('vendedor.tienda.edit') }}#imagenes"><x-seller-icon name="edit"/>Editar portada</a><span class="seller-cover-label">TU TIENDA EN NEXOECO</span></div>
    <div class="seller-store-identity"><div class="seller-store-logo">@if($logo)<img src="{{ $logo }}" alt="Logo de {{ $tienda->nombre_tienda }}">@else<x-seller-icon/>@endif<a href="{{ route('vendedor.tienda.edit') }}#imagenes" aria-label="Editar logo"><x-seller-icon name="edit"/></a></div>
    <div class="seller-store-title"><h1>{{ $tienda->nombre_tienda }}</h1><a href="{{ route('vendedor.tienda.edit') }}#identidad" class="seller-edit-icon" aria-label="Editar datos de la tienda"><x-seller-icon name="edit"/></a></div>
    <div class="seller-store-meta"><span><x-seller-icon name="star"/><strong>{{ $rating ? number_format($rating, 1) : 'Sin calificaciones' }}</strong>@if($rating) / 5 · {{ $tienda->opiniones_count }} opiniones @endif</span><span><x-seller-icon name="clock"/>Desde {{ $tienda->fecha_creacion?->translatedFormat('M Y') ?? 'su registro' }}</span><span><x-seller-icon name="heart"/>{{ $favorites }} {{ $favorites === 1 ? 'favorito' : 'favoritos' }}</span><span class="seller-verified"><x-seller-icon name="shield"/>Vendedor autorizado</span></div>
    <p class="seller-store-description">{{ $tienda->descripcion_tienda }}</p>
    <div class="seller-hero-actions"><a class="seller-button" href="{{ route('vendedor.productos.create') }}"><x-seller-icon name="plus"/>Agregar producto</a><a class="seller-button secondary" href="{{ route('tiendas.show', $tienda) }}">Ver mi tienda en el marketplace</a></div>
    </div>
</section>
<div class="seller-section-title"><div><span class="buyer-eyebrow">Todo en un vistazo</span><h2>Resumen de tu tienda</h2></div><span class="seller-live-note">Datos de tu actividad real</span></div>
<div class="seller-stats">
@foreach([['box', 'Productos publicados', $tienda->productos_count, 'En tu catálogo'], ['heart', 'Favoritos de productos', $productFavorites, 'Guardados por compradores'], ['chat', 'Opiniones de productos', $productReviews, 'Reseñas recibidas'], ['star', 'Calificación de la tienda', $rating ? number_format($rating, 1).' / 5' : 'Sin reseñas', $tienda->opiniones_count.' opiniones']] as [$icon, $title, $value, $caption])
<article class="seller-card seller-stat"><span class="seller-icon"><x-seller-icon name="{{ $icon }}"/></span><div><h3>{{ $title }}</h3><strong>{{ $value }}</strong><p>{{ $caption }}</p></div></article>
@endforeach
</div>
<div class="seller-details-grid">
<article class="seller-card"><div class="seller-card-title"><span class="seller-icon"><x-seller-icon/></span><h2>Datos del negocio</h2><a href="{{ route('vendedor.tienda.edit') }}" aria-label="Editar datos del negocio"><x-seller-icon name="edit"/></a></div><dl class="seller-data-list"><div><dt>Razón social</dt><dd>{{ $tienda->razon_social ?: $tienda->nombre_tienda }}</dd></div><div><dt>Giro</dt><dd>{{ $tienda->giro ?: 'Por completar' }}</dd></div><div><dt>Tipo</dt><dd>{{ ['local' => 'Local físico', 'servicios' => 'Servicios', 'en_linea' => 'Tienda en línea', 'mixto' => 'Local y venta en línea'][$tienda->tipo_negocio] ?? 'Por completar' }}</dd></div><div><dt>Contacto</dt><dd>{{ $tienda->telefono ?: 'Por completar' }}</dd></div></dl><span class="account-pill">Visible en el marketplace</span></article>
<article class="seller-card"><div class="seller-card-title"><span class="seller-icon green"><x-seller-icon name="shield"/></span><h2>Documentación del vendedor</h2></div>@if($approved)<p class="seller-help">Solicitud aprobada{{ $solicitud->fecha_revision ? ' el '.$solicitud->fecha_revision->format('d/m/Y') : '' }}.</p><ul class="seller-document-list">@foreach($solicitud->documentos as $documento)<li><x-seller-icon name="shield"/><span>{{ ['identificacion_frente' => 'Identificación oficial', 'identificacion_reverso' => 'Reverso de identificación', 'comprobante_domicilio' => 'Comprobante de domicilio', 'constancia_fiscal' => 'Constancia de situación fiscal'][$documento->tipo_documento] ?? str_replace('_', ' ', $documento->tipo_documento) }}</span><span class="seller-document-status">Revisado</span></li>@endforeach</ul>@else<p class="seller-help">Tu cuenta tiene el rol de vendedor habilitado.</p><p class="seller-help">No hay una solicitud con documentación aprobada asociada a esta cuenta.</p>@endif</article>
<article class="seller-card"><div class="seller-card-title"><span class="seller-icon"><x-seller-icon name="chart"/></span><h2>Desempeño del catálogo</h2></div><dl class="seller-data-list"><div><dt>Productos</dt><dd>{{ $tienda->productos_count }}</dd></div><div><dt>Categorías con productos</dt><dd>{{ $categorias->count() }}</dd></div><div><dt>Favoritos de la tienda</dt><dd>{{ $favorites }}</dd></div><div><dt>Reseñas de la tienda</dt><dd>{{ $tienda->opiniones_count }}</dd></div></dl><a class="seller-text-link" href="{{ route('vendedor.productos.index') }}">Administrar mis productos →</a></article>
</div>
<div class="seller-section-title"><div><h2>Categorías de tu catálogo</h2><p>Organiza lo que ofreces y encuentra tus productos por categoría.</p></div></div>
@if($categorias->isEmpty())<div class="seller-empty"><span class="seller-icon"><x-seller-icon name="box"/></span><h3>Aún no tienes categorías con productos</h3><p>Al publicar tu primer producto podrás elegir una categoría o crear una nueva.</p><a class="seller-text-link" href="{{ route('vendedor.productos.create') }}">Publicar mi primer producto →</a></div>@else<div class="seller-category-list"><a class="seller-category" href="{{ route('vendedor.productos.index') }}">Todos <span>{{ $tienda->productos_count }}</span></a>@foreach($categorias as $categoria)<a class="seller-category" href="{{ route('vendedor.productos.index', ['categoria' => $categoria->getKey()]) }}">{{ $categoria->nombre_categoria }}<span>{{ $categoria->productos_count }}</span></a>@endforeach</div>@endif
<div class="seller-section-title"><div><h2>Productos con más favoritos</h2><p>Los productos que más guardan tus compradores.</p></div><a class="seller-text-link" href="{{ route('vendedor.productos.index') }}">Ver todos →</a></div>
@if($productFavorites === 0)<div class="seller-empty"><span class="seller-icon"><x-seller-icon name="heart"/></span><h3>Tus próximos favoritos empiezan aquí</h3><p>Cuando los compradores guarden tus productos, aquí verás los más populares.</p></div>@else<div class="seller-product-grid">@foreach($populares->where('favoritos_count', '>', 0) as $producto)@include('vendedor.productos.card', ['showFavorites' => true])@endforeach</div>@endif
<div class="seller-details-grid seller-business-bottom"><article class="seller-card"><div class="seller-card-title"><span class="seller-icon"><x-seller-icon name="pin"/></span><h2>Ubicación y contacto</h2></div><p>{{ $tienda->direccion ?: 'Completa la dirección de tu tienda.' }}{{ $tienda->colonia ? ', '.$tienda->colonia : '' }}</p><p class="seller-help">{{ implode(', ', array_filter([$tienda->ciudad, $tienda->estado, $tienda->codigo_postal])) }}</p>@if($tienda->latitud !== null && $tienda->longitud !== null)<a class="seller-text-link" target="_blank" rel="noopener" href="https://www.openstreetmap.org/?mlat={{ $tienda->latitud }}&mlon={{ $tienda->longitud }}#map=17/{{ $tienda->latitud }}/{{ $tienda->longitud }}">Ver ubicación en el mapa ↗</a>@endif<p class="seller-help">{{ $tienda->email_contacto }}</p></article><article class="seller-card seller-hours-card"><div class="seller-card-title"><span class="seller-icon"><x-seller-icon name="clock"/></span><h2>Horario de atención</h2><a href="{{ route('vendedor.tienda.edit') }}#horarios" aria-label="Editar horarios"><x-seller-icon name="edit"/></a></div>@include('marketplace.partials.business-hours')</article></div>
@endsection
