@extends('layouts.marketplace')
@section('title', $tienda->nombre_tienda.' | NexoEco')
@section('content')
<main class="nexo-container public-store-page">
    @php($marketRoute = auth()->check() ? 'comprador.dashboard' : 'marketplace.index')

    <section class="public-store-hero">
        <div class="store-public-cover"><a href="{{ route($marketRoute) }}" class="market-back-button public-image-back" data-back-marketplace><x-market-icon name="arrow"/>Volver</a>@if($tienda->portada_tienda)<img src="{{ \App\Support\MarketplaceImage::url($tienda->portada_tienda) }}" alt="Portada de {{ $tienda->nombre_tienda }}">@else<div class="public-store-cover-empty"><x-market-icon name="store"/></div>@endif</div>
        <div class="public-store-identity">
            <div class="public-store-logo">@if($logoTienda)<img src="{{ $logoTienda }}" alt="Logo de {{ $tienda->nombre_tienda }}">@else<x-market-icon name="store"/>@endif</div>
            <div class="public-store-title"><h1>{{ $tienda->nombre_tienda }}</h1>@include('marketplace.partials.favorite-button', ['tipo' => 'tiendas', 'item' => $tienda])</div>
            <div class="public-store-meta"><span><x-market-icon name="star"/>{{ $tienda->opiniones_count ? number_format($tienda->opiniones_avg_calificacion, 1).' / 5 · '.$tienda->opiniones_count.' opiniones' : 'Sin calificaciones' }}</span><span><x-seller-icon name="box"/>{{ $productos->total() }} {{ $productos->total() === 1 ? 'producto' : 'productos' }}</span>@if($tienda->fecha_creacion)<span><x-seller-icon name="clock"/>Desde {{ $tienda->fecha_creacion->format('Y') }}</span>@endif @if($tienda->user?->tieneTipo('vendedor'))<span class="public-store-approved"><x-seller-icon name="shield"/>Vendedor autorizado</span>@endif</div>
            <p class="public-store-description">{{ $tienda->descripcion_tienda ?: 'Conoce los productos de este negocio de tu comunidad.' }}</p>
        </div>
    </section>
    <div class="store-info-tiles" aria-label="Información del negocio">
        <button type="button" class="store-info-tile" data-dialog-open="store-contact-dialog" aria-haspopup="dialog"><span class="store-tile-icon"><x-seller-icon name="pin"/></span><span><strong>Visita y contacta al negocio</strong><small>{{ $tienda->ciudad ? $tienda->ciudad.($tienda->estado ? ', '.$tienda->estado : '') : 'Ubicación y contacto' }}</small></span><x-market-icon name="chevron"/></button>
        <button type="button" class="store-info-tile" data-dialog-open="store-hours-dialog" aria-haspopup="dialog"><span class="store-tile-icon"><x-seller-icon name="clock"/></span><span><strong>Horarios de atención</strong><small>Consulta los días y las horas de atención</small></span><x-market-icon name="chevron"/></button>
    </div>
    <section id="productos" class="public-store-products"><div class="buyer-section-heading"><div><h2>Productos de la tienda</h2><p>Explora el catálogo de {{ $tienda->nombre_tienda }}.</p></div></div>
        @if($productos->count())<div class="buyer-grid marketplace-products-grid">@foreach($productos as $producto)@include('marketplace.partials.product-card')@endforeach</div>@if($productos->hasPages())<div class="market-pagination">{{ $productos->links() }}</div>@endif
        @else<div class="buyer-empty"><h2>Esta tienda todavía no tiene productos</h2><p>Puedes seguir explorando otros emprendimientos de NexoEco.</p><a class="buyer-button" href="{{ route($marketRoute) }}">Volver al marketplace</a></div>@endif
    </section>
    @include('marketplace.partials.opiniones', ['tipo' => 'tiendas', 'item' => $tienda])
    <dialog id="store-contact-dialog" class="store-info-dialog" aria-labelledby="store-contact-title" data-store-dialog><div class="store-dialog-heading"><div><span class="buyer-eyebrow">{{ $tienda->nombre_tienda }}</span><h2 id="store-contact-title">Visita y contacta al negocio</h2></div><button type="button" data-dialog-close aria-label="Cerrar información de contacto"><x-market-icon name="close"/></button></div><div class="store-dialog-body">
        @if($tienda->direccion)<p class="store-dialog-address"><x-seller-icon name="pin"/><span>{{ $tienda->direccion }}{{ $tienda->colonia ? ', '.$tienda->colonia : '' }}<small>{{ implode(', ', array_filter([$tienda->ciudad, $tienda->estado, $tienda->codigo_postal])) }}</small></span></p>@else<p class="buyer-muted">El vendedor aún no ha indicado su dirección.</p>@endif
        @if($tienda->referencias)<p class="buyer-muted">{{ $tienda->referencias }}</p>@endif
        <div class="store-contact-links">@if($tienda->telefono)<a href="tel:{{ preg_replace('/[^+0-9]/', '', $tienda->telefono) }}">Teléfono: {{ $tienda->telefono }}</a>@endif @if($tienda->email_contacto)<a href="mailto:{{ $tienda->email_contacto }}">{{ $tienda->email_contacto }}</a>@endif @if($tienda->sitio_web && preg_match('#^https?://#i', $tienda->sitio_web))<a href="{{ $tienda->sitio_web }}" target="_blank" rel="noopener noreferrer">Sitio web o red social ↗</a>@endif</div>
        @if($tienda->latitud !== null && $tienda->longitud !== null)<iframe class="store-location-map" title="Ubicación de {{ $tienda->nombre_tienda }}" data-map-src="https://www.openstreetmap.org/export/embed.html?bbox={{ $tienda->longitud - .006 }}%2C{{ $tienda->latitud - .004 }}%2C{{ $tienda->longitud + .006 }}%2C{{ $tienda->latitud + .004 }}&amp;layer=mapnik&amp;marker={{ $tienda->latitud }}%2C{{ $tienda->longitud }}"></iframe><a class="seller-text-link" target="_blank" rel="noopener" href="https://www.openstreetmap.org/?mlat={{ $tienda->latitud }}&mlon={{ $tienda->longitud }}#map=17/{{ $tienda->latitud }}/{{ $tienda->longitud }}">Abrir mapa ↗</a>@endif
        @if(!$tienda->telefono && !$tienda->email_contacto && !$tienda->sitio_web)<p class="buyer-muted">El vendedor aún no ha agregado medios de contacto.</p>@endif
    </div></dialog>
    <dialog id="store-hours-dialog" class="store-info-dialog" aria-labelledby="store-hours-title" data-store-dialog><div class="store-dialog-heading"><div><span class="buyer-eyebrow">{{ $tienda->nombre_tienda }}</span><h2 id="store-hours-title">Horario de atención</h2></div><button type="button" data-dialog-close aria-label="Cerrar horarios"><x-market-icon name="close"/></button></div><div class="store-dialog-body">@include('marketplace.partials.business-hours')<p class="buyer-muted">Hora local de Manzanillo.</p>@if($tienda->servicios)<h3>Modalidades de atención</h3><div class="store-service-pills">@foreach($tienda->servicios as $service)<span class="account-pill">{{ ['local' => 'Atención en local', 'recoger' => 'Recoger en tienda', 'domicilio' => 'Entrega a domicilio', 'envios' => 'Envíos'][$service] ?? $service }}</span>@endforeach</div>@endif</div></dialog>
</main>
@endsection