@extends('layouts.seller-panel')
@section('title', $producto ? 'Editar producto | NexoEco' : 'Publicar producto | NexoEco')
@section('seller-content')
<div class="seller-heading"><div><span class="buyer-eyebrow">{{ $tienda->nombre_tienda }}</span><h1>{{ $producto ? 'Editar producto' : 'Un nuevo producto para tu tienda' }}</h1><p>Una buena foto y una descripción clara ayudan a tus compradores a decidir.</p></div><a class="seller-button secondary" href="{{ route('vendedor.productos.index') }}">Volver a productos</a></div>
<form method="POST" action="{{ $producto ? route('vendedor.productos.update', $producto) : route('vendedor.productos.store') }}" enctype="multipart/form-data" class="seller-form seller-card seller-product-form" data-shop-form>@csrf @if($producto)@method('PUT')@endif
<div class="seller-fields"><div class="seller-field full"><label for="nombre_producto">Nombre del producto *</label><input name="nombre_producto" id="nombre_producto" maxlength="150" value="{{ old('nombre_producto', $producto?->nombre_producto) }}" required></div><div class="seller-field"><label for="precio">Precio en MXN *</label><input type="number" min="0.01" max="99999999.99" step="0.01" name="precio" id="precio" value="{{ old('precio', $producto?->precio) }}" required></div><div class="seller-field"><label for="id_categoria">Categoría *</label><select name="id_categoria" id="id_categoria"><option value="">Selecciona una categoría</option>@foreach($categorias as $categoria)<option value="{{ $categoria->getKey() }}" @selected((string)old('id_categoria', $producto?->id_categoria) === (string)$categoria->getKey())>{{ $categoria->nombre_categoria }}</option>@endforeach</select></div><div class="seller-field full"><label for="nueva_categoria">O crea una categoría nueva (opcional)</label><input name="nueva_categoria" id="nueva_categoria" maxlength="100" value="{{ old('nueva_categoria') }}" placeholder="Ej. Cerámica artesanal"><p class="seller-help">Si escribes una nueva categoría, se usará para este producto y quedará disponible en el catálogo.</p></div><div class="seller-field full"><label for="descripcion">Descripción *</label><textarea name="descripcion" id="descripcion" rows="5" maxlength="5000" required placeholder="Materiales, medidas, características y lo que incluye tu producto">{{ old('descripcion', $producto?->descripcion) }}</textarea></div></div>
@php($image = \App\Support\MarketplaceImage::url($producto?->imagenPrincipal?->imagen_url ?: $producto?->imagen_url))
<div class="seller-upload"><div class="seller-upload-preview product" data-image-container><img data-shop-image-preview="imagen" @if($image) src="{{ $image }}" @else hidden @endif alt="Vista previa del producto"><span data-image-placeholder @if($image) hidden @endif><x-seller-icon name="box"/>Foto del producto</span></div><label for="imagen">Imagen principal{{ !$producto ? ' *' : '' }}</label><input type="file" name="imagen" id="imagen" accept="image/jpeg,image/png,image/webp" data-shop-image-input="imagen" @required(!$producto)><p class="seller-help">JPG, PNG o WebP. Máximo 5 MB.{{ $producto ? ' Deja vacío para conservar la imagen.' : '' }}</p></div><div class="seller-form-actions"><p>Al guardar, el producto se mostrará en el marketplace.</p><button class="seller-button" type="submit">{{ $producto ? 'Guardar cambios' : 'Publicar producto' }}</button></div>
</form>
@endsection
