@extends('layouts.admin-panel')
@section('title', 'Consultas de soporte · NexoEco')
@section('admin-content')
<div class="admin-heading"><span class="buyer-eyebrow">Administración · Soporte</span><h1>Consultas de los usuarios</h1><p class="buyer-description">Revisa los mensajes, responde y marca las consultas resueltas.</p></div>
<nav class="buyer-tabs" aria-label="Estado de consultas"><a class="{{ !request('estado') ? 'active' : '' }}" href="{{ route('admin.consultas.index') }}">Todas</a>@foreach(['abierta' => 'Recibidas', 'en_proceso' => 'En proceso', 'cerrada' => 'Resueltas'] as $state => $label)<a class="{{ request('estado') === $state ? 'active' : '' }}" href="{{ route('admin.consultas.index', ['estado' => $state]) }}">{{ $label }} · {{ $conteos[$state] ?? 0 }}</a>@endforeach</nav>
<form class="buyer-form admin-filters" method="GET">@if(request('estado'))<input type="hidden" name="estado" value="{{ request('estado') }}">@endif<div class="buyer-field"><label for="q">Buscar consulta</label><input id="q" name="q" value="{{ request('q') }}" maxlength="100" placeholder="Asunto, mensaje o usuario"></div><button class="buyer-button" type="submit">Buscar</button></form>
@forelse($consultas as $ticket)<article class="buyer-panel"><div class="buyer-row"><div><h2><a href="{{ route('admin.consultas.show', $ticket) }}">#{{ $ticket->id }} · {{ $ticket->asunto }}</a></h2><p>{{ $ticket->usuario->nombre_completo ?: $ticket->usuario->name }} · {{ $ticket->usuario->email }}</p></div><span class="account-pill {{ $ticket->estado !== 'cerrada' ? 'pending' : '' }}">{{ ['abierta' => 'Recibida', 'en_proceso' => 'En proceso', 'cerrada' => 'Resuelta'][$ticket->estado] ?? $ticket->estado }}</span></div><p style="margin:14px 0;">{{ \Illuminate\Support\Str::limit($ticket->mensaje, 180) }}</p><div class="buyer-row"><span class="buyer-muted">{{ $ticket->respuestas_count }} mensajes · Actualizada {{ $ticket->updated_at->format('d/m/Y H:i') }}</span><a class="buyer-text-link" href="{{ route('admin.consultas.show', $ticket) }}">Abrir y responder</a></div></article>@empty<div class="buyer-empty"><h2>No hay consultas con estos filtros</h2><p>Los mensajes de Contacto aparecerán aquí.</p></div>@endforelse
{{ $consultas->links() }}
@endsection
